#############################################################################
# Makefile for building: EngineProject.app/Contents/MacOS/EngineProject
# Generated by qmake (3.1) (Qt 6.6.0)
# Project:  EngineProject.pro
# Template: app
# Command: /Users/alexanderstorozhenko/Qt/6.6.0/macos/bin/qmake -o Makefile EngineProject.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -I/../opt/local/include -I/../opt/local/include -I/../opt/local/include -I../../../Qt/6.6.0/macos/lib/QtWidgets.framework/Headers -I../../../Qt/6.6.0/macos/lib/QtGui.framework/Headers -I../../../Qt/6.6.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/6.6.0/macos/mkspecs/macx-clang -F/Users/alexanderstorozhenko/Qt/6.6.0/macos/lib
QMAKE         = /Users/alexanderstorozhenko/Qt/6.6.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/alexanderstorozhenko/Qt/6.6.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/alexanderstorozhenko/Qt/6.6.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = EngineProject1.0.0
DISTDIR = /Users/alexanderstorozhenko/Desktop/CSE201/Raytracing/.tmp/EngineProject1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/alexanderstorozhenko/Qt/6.6.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/alexanderstorozhenko/Qt/6.6.0/macos/lib -L/Users/alexanderstorozhenko/Desktop/CSE201/Raytracing/../../../../../../opt/local/lib/ -lGLEW -lglm_shared -lglfw.3.3 -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		imgui/imgui.cpp \
		imgui/imgui_demo.cpp \
		imgui/imgui_draw.cpp \
		imgui/imgui_tables.cpp \
		imgui/imgui_widgets.cpp \
		imgui/backends/imgui_impl_glfw.cpp \
		imgui/backends/imgui_impl_opengl3.cpp 
OBJECTS       = main.o \
		imgui.o \
		imgui_demo.o \
		imgui_draw.o \
		imgui_tables.o \
		imgui_widgets.o \
		imgui_impl_glfw.o \
		imgui_impl_opengl3.o
DIST          = fragmentshader.shader \
		vertexshader.shader \
		../../../Qt/6.6.0/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.6.0/macos/mkspecs/common/unix.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/mac.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/macx.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/clang.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.6.0/macos/mkspecs/qconfig.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.6.0/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qml_debug.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qt.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/resources.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/moc.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/uic.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/lex.prf \
		EngineProject.pro shader.h \
		imgui/imgui.h \
		imgui/imconfig.h \
		imgui/imgui_internal.h \
		imgui/imstb_rectpack.h \
		imgui/imstb_textedit.h \
		imgui/imstb_truetype.h \
		imgui/backends/imgui_impl_glfw.h \
		imgui/backends/imgui_impl_opengl3.h main.cpp \
		imgui/imgui.cpp \
		imgui/imgui_demo.cpp \
		imgui/imgui_draw.cpp \
		imgui/imgui_tables.cpp \
		imgui/imgui_widgets.cpp \
		imgui/backends/imgui_impl_glfw.cpp \
		imgui/backends/imgui_impl_opengl3.cpp
QMAKE_TARGET  = EngineProject
DESTDIR       = 
TARGET        = EngineProject.app/Contents/MacOS/EngineProject

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = x86_64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/alexanderstorozhenko/Desktop/CSE201/Raytracing/EngineProject.pro


include /Users/alexanderstorozhenko/Qt/6.6.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

EngineProject.app/Contents/MacOS/EngineProject:  $(OBJECTS)  
	@test -d EngineProject.app/Contents/MacOS/ || mkdir -p EngineProject.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EngineProject.pro ../../../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf ../../../Qt/6.6.0/macos/mkspecs/features/spec_pre.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/device_config.prf \
		../../../Qt/6.6.0/macos/mkspecs/common/unix.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/mac.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/macx.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/sanitize.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/gcc-base.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/clang.conf \
		../../../Qt/6.6.0/macos/mkspecs/common/clang-mac.conf \
		../../../Qt/6.6.0/macos/mkspecs/qconfig.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../../../Qt/6.6.0/macos/mkspecs/features/qt_functions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qt_config.prf \
		../../../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf \
		../../../Qt/6.6.0/macos/mkspecs/features/spec_post.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/exclusive_builds.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/sdk.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/toolchain.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/toolchain.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/default_pre.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/default_pre.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/resolve_config.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/default_post.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/default_post.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/objective_c.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qml_debug.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/mac.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/warn_on.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/permissions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qt.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/resources_functions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/resources.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/moc.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/unix/opengl.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/uic.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/unix/thread.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/qmake_use.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/file_copies.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/rez.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/testcase_targets.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/exceptions.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/yacc.prf \
		../../../Qt/6.6.0/macos/mkspecs/features/lex.prf \
		EngineProject.pro \
		../../../Qt/6.6.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../../Qt/6.6.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../../Qt/6.6.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile EngineProject.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../../../Qt/6.6.0/macos/mkspecs/features/spec_pre.prf:
../../../Qt/6.6.0/macos/mkspecs/features/device_config.prf:
../../../Qt/6.6.0/macos/mkspecs/common/unix.conf:
../../../Qt/6.6.0/macos/mkspecs/common/mac.conf:
../../../Qt/6.6.0/macos/mkspecs/common/macx.conf:
../../../Qt/6.6.0/macos/mkspecs/common/sanitize.conf:
../../../Qt/6.6.0/macos/mkspecs/common/gcc-base.conf:
../../../Qt/6.6.0/macos/mkspecs/common/gcc-base-mac.conf:
../../../Qt/6.6.0/macos/mkspecs/common/clang.conf:
../../../Qt/6.6.0/macos/mkspecs/common/clang-mac.conf:
../../../Qt/6.6.0/macos/mkspecs/qconfig.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../../../Qt/6.6.0/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../../../Qt/6.6.0/macos/mkspecs/features/qt_functions.prf:
../../../Qt/6.6.0/macos/mkspecs/features/qt_config.prf:
../../../Qt/6.6.0/macos/mkspecs/macx-clang/qmake.conf:
../../../Qt/6.6.0/macos/mkspecs/features/spec_post.prf:
../../../Qt/6.6.0/macos/mkspecs/features/exclusive_builds.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/sdk.prf:
../../../Qt/6.6.0/macos/mkspecs/features/toolchain.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/toolchain.prf:
../../../Qt/6.6.0/macos/mkspecs/features/default_pre.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/default_pre.prf:
../../../Qt/6.6.0/macos/mkspecs/features/resolve_config.prf:
../../../Qt/6.6.0/macos/mkspecs/features/default_post.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/default_post.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/objective_c.prf:
../../../Qt/6.6.0/macos/mkspecs/features/qml_debug.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/mac.prf:
../../../Qt/6.6.0/macos/mkspecs/features/warn_on.prf:
../../../Qt/6.6.0/macos/mkspecs/features/permissions.prf:
../../../Qt/6.6.0/macos/mkspecs/features/qt.prf:
../../../Qt/6.6.0/macos/mkspecs/features/resources_functions.prf:
../../../Qt/6.6.0/macos/mkspecs/features/resources.prf:
../../../Qt/6.6.0/macos/mkspecs/features/moc.prf:
../../../Qt/6.6.0/macos/mkspecs/features/unix/opengl.prf:
../../../Qt/6.6.0/macos/mkspecs/features/uic.prf:
../../../Qt/6.6.0/macos/mkspecs/features/unix/thread.prf:
../../../Qt/6.6.0/macos/mkspecs/features/qmake_use.prf:
../../../Qt/6.6.0/macos/mkspecs/features/file_copies.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/rez.prf:
../../../Qt/6.6.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/6.6.0/macos/mkspecs/features/testcase_targets.prf:
../../../Qt/6.6.0/macos/mkspecs/features/exceptions.prf:
../../../Qt/6.6.0/macos/mkspecs/features/yacc.prf:
../../../Qt/6.6.0/macos/mkspecs/features/lex.prf:
EngineProject.pro:
../../../Qt/6.6.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../../Qt/6.6.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../../Qt/6.6.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile EngineProject.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

EngineProject.app/Contents/PkgInfo: 
	@test -d EngineProject.app/Contents || mkdir -p EngineProject.app/Contents
	@$(DEL_FILE) EngineProject.app/Contents/PkgInfo
	@echo "APPL????" > EngineProject.app/Contents/PkgInfo
EngineProject.app/Contents/Info.plist: 
	@test -d EngineProject.app/Contents || mkdir -p EngineProject.app/Contents
	@$(DEL_FILE) EngineProject.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../../../Qt/6.6.0/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,AleksandrStorozhenko.EngineProject,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},AleksandrStorozhenko.EngineProject,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,EngineProject,g" -e "s,@LIBRARY@,EngineProject,g" -e "s,\$${EXECUTABLE_NAME},EngineProject,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >EngineProject.app/Contents/Info.plist

all: Makefile \
		EngineProject.app/Contents/PkgInfo \
		EngineProject.app/Contents/Info.plist EngineProject.app/Contents/MacOS/EngineProject

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents shader.h imgui/imgui.h imgui/imconfig.h imgui/imgui_internal.h imgui/imstb_rectpack.h imgui/imstb_textedit.h imgui/imstb_truetype.h imgui/backends/imgui_impl_glfw.h imgui/backends/imgui_impl_opengl3.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp imgui/imgui.cpp imgui/imgui_demo.cpp imgui/imgui_draw.cpp imgui/imgui_tables.cpp imgui/imgui_widgets.cpp imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r EngineProject.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /../opt/local/include/GL/glew.h \
		/../opt/local/include/GLFW/glfw3.h \
		/../opt/local/include/glm/glm.hpp \
		/../opt/local/include/glm/detail/_fixes.hpp \
		/../opt/local/include/glm/detail/setup.hpp \
		/../opt/local/include/glm/simd/platform.h \
		/../opt/local/include/glm/simd/neon.h \
		/../opt/local/include/glm/fwd.hpp \
		/../opt/local/include/glm/detail/qualifier.hpp \
		/../opt/local/include/glm/vec2.hpp \
		/../opt/local/include/glm/ext/vector_bool2.hpp \
		/../opt/local/include/glm/detail/type_vec2.hpp \
		/../opt/local/include/glm/detail/_swizzle.hpp \
		/../opt/local/include/glm/detail/_swizzle_func.hpp \
		/../opt/local/include/glm/detail/type_vec2.inl \
		/../opt/local/include/glm/detail/compute_vector_relational.hpp \
		/../opt/local/include/glm/ext/vector_bool2_precision.hpp \
		/../opt/local/include/glm/ext/vector_float2.hpp \
		/../opt/local/include/glm/ext/vector_float2_precision.hpp \
		/../opt/local/include/glm/ext/vector_double2.hpp \
		/../opt/local/include/glm/ext/vector_double2_precision.hpp \
		/../opt/local/include/glm/ext/vector_int2.hpp \
		/../opt/local/include/glm/ext/vector_int2_sized.hpp \
		/../opt/local/include/glm/ext/scalar_int_sized.hpp \
		/../opt/local/include/glm/ext/vector_uint2.hpp \
		/../opt/local/include/glm/ext/vector_uint2_sized.hpp \
		/../opt/local/include/glm/ext/scalar_uint_sized.hpp \
		/../opt/local/include/glm/vec3.hpp \
		/../opt/local/include/glm/ext/vector_bool3.hpp \
		/../opt/local/include/glm/detail/type_vec3.hpp \
		/../opt/local/include/glm/detail/type_vec3.inl \
		/../opt/local/include/glm/ext/vector_bool3_precision.hpp \
		/../opt/local/include/glm/ext/vector_float3.hpp \
		/../opt/local/include/glm/ext/vector_float3_precision.hpp \
		/../opt/local/include/glm/ext/vector_double3.hpp \
		/../opt/local/include/glm/ext/vector_double3_precision.hpp \
		/../opt/local/include/glm/ext/vector_int3.hpp \
		/../opt/local/include/glm/ext/vector_int3_sized.hpp \
		/../opt/local/include/glm/ext/vector_uint3.hpp \
		/../opt/local/include/glm/ext/vector_uint3_sized.hpp \
		/../opt/local/include/glm/vec4.hpp \
		/../opt/local/include/glm/ext/vector_bool4.hpp \
		/../opt/local/include/glm/detail/type_vec4.hpp \
		/../opt/local/include/glm/detail/type_vec4.inl \
		/../opt/local/include/glm/detail/type_vec4_simd.inl \
		/../opt/local/include/glm/ext/vector_bool4_precision.hpp \
		/../opt/local/include/glm/ext/vector_float4.hpp \
		/../opt/local/include/glm/ext/vector_float4_precision.hpp \
		/../opt/local/include/glm/ext/vector_double4.hpp \
		/../opt/local/include/glm/ext/vector_double4_precision.hpp \
		/../opt/local/include/glm/ext/vector_int4.hpp \
		/../opt/local/include/glm/ext/vector_int4_sized.hpp \
		/../opt/local/include/glm/ext/vector_uint4.hpp \
		/../opt/local/include/glm/ext/vector_uint4_sized.hpp \
		/../opt/local/include/glm/mat2x2.hpp \
		/../opt/local/include/glm/ext/matrix_double2x2.hpp \
		/../opt/local/include/glm/detail/type_mat2x2.hpp \
		/../opt/local/include/glm/detail/type_mat2x2.inl \
		/../opt/local/include/glm/matrix.hpp \
		/../opt/local/include/glm/mat2x3.hpp \
		/../opt/local/include/glm/ext/matrix_double2x3.hpp \
		/../opt/local/include/glm/detail/type_mat2x3.hpp \
		/../opt/local/include/glm/detail/type_mat2x3.inl \
		/../opt/local/include/glm/ext/matrix_double2x3_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float2x3.hpp \
		/../opt/local/include/glm/ext/matrix_float2x3_precision.hpp \
		/../opt/local/include/glm/mat2x4.hpp \
		/../opt/local/include/glm/ext/matrix_double2x4.hpp \
		/../opt/local/include/glm/detail/type_mat2x4.hpp \
		/../opt/local/include/glm/detail/type_mat2x4.inl \
		/../opt/local/include/glm/ext/matrix_double2x4_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float2x4.hpp \
		/../opt/local/include/glm/ext/matrix_float2x4_precision.hpp \
		/../opt/local/include/glm/mat3x2.hpp \
		/../opt/local/include/glm/ext/matrix_double3x2.hpp \
		/../opt/local/include/glm/detail/type_mat3x2.hpp \
		/../opt/local/include/glm/detail/type_mat3x2.inl \
		/../opt/local/include/glm/ext/matrix_double3x2_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float3x2.hpp \
		/../opt/local/include/glm/ext/matrix_float3x2_precision.hpp \
		/../opt/local/include/glm/mat3x3.hpp \
		/../opt/local/include/glm/ext/matrix_double3x3.hpp \
		/../opt/local/include/glm/detail/type_mat3x3.hpp \
		/../opt/local/include/glm/detail/type_mat3x3.inl \
		/../opt/local/include/glm/ext/matrix_double3x3_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float3x3.hpp \
		/../opt/local/include/glm/ext/matrix_float3x3_precision.hpp \
		/../opt/local/include/glm/mat3x4.hpp \
		/../opt/local/include/glm/ext/matrix_double3x4.hpp \
		/../opt/local/include/glm/detail/type_mat3x4.hpp \
		/../opt/local/include/glm/detail/type_mat3x4.inl \
		/../opt/local/include/glm/ext/matrix_double3x4_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float3x4.hpp \
		/../opt/local/include/glm/ext/matrix_float3x4_precision.hpp \
		/../opt/local/include/glm/mat4x2.hpp \
		/../opt/local/include/glm/ext/matrix_double4x2.hpp \
		/../opt/local/include/glm/detail/type_mat4x2.hpp \
		/../opt/local/include/glm/detail/type_mat4x2.inl \
		/../opt/local/include/glm/ext/matrix_double4x2_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float4x2.hpp \
		/../opt/local/include/glm/ext/matrix_float4x2_precision.hpp \
		/../opt/local/include/glm/mat4x3.hpp \
		/../opt/local/include/glm/ext/matrix_double4x3.hpp \
		/../opt/local/include/glm/detail/type_mat4x3.hpp \
		/../opt/local/include/glm/detail/type_mat4x3.inl \
		/../opt/local/include/glm/ext/matrix_double4x3_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float4x3.hpp \
		/../opt/local/include/glm/ext/matrix_float4x3_precision.hpp \
		/../opt/local/include/glm/mat4x4.hpp \
		/../opt/local/include/glm/ext/matrix_double4x4.hpp \
		/../opt/local/include/glm/detail/type_mat4x4.hpp \
		/../opt/local/include/glm/detail/type_mat4x4.inl \
		/../opt/local/include/glm/detail/type_mat4x4_simd.inl \
		/../opt/local/include/glm/ext/matrix_double4x4_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float4x4.hpp \
		/../opt/local/include/glm/ext/matrix_float4x4_precision.hpp \
		/../opt/local/include/glm/detail/func_matrix.inl \
		/../opt/local/include/glm/geometric.hpp \
		/../opt/local/include/glm/detail/func_geometric.inl \
		/../opt/local/include/glm/exponential.hpp \
		/../opt/local/include/glm/detail/type_vec1.hpp \
		/../opt/local/include/glm/detail/type_vec1.inl \
		/../opt/local/include/glm/detail/func_exponential.inl \
		/../opt/local/include/glm/vector_relational.hpp \
		/../opt/local/include/glm/detail/func_vector_relational.inl \
		/../opt/local/include/glm/detail/func_vector_relational_simd.inl \
		/../opt/local/include/glm/detail/_vectorize.hpp \
		/../opt/local/include/glm/detail/func_exponential_simd.inl \
		/../opt/local/include/glm/simd/exponential.h \
		/../opt/local/include/glm/common.hpp \
		/../opt/local/include/glm/detail/func_common.inl \
		/../opt/local/include/glm/detail/compute_common.hpp \
		/../opt/local/include/glm/detail/func_common_simd.inl \
		/../opt/local/include/glm/simd/common.h \
		/../opt/local/include/glm/detail/func_geometric_simd.inl \
		/../opt/local/include/glm/simd/geometric.h \
		/../opt/local/include/glm/detail/func_matrix_simd.inl \
		/../opt/local/include/glm/simd/matrix.h \
		/../opt/local/include/glm/ext/matrix_double2x2_precision.hpp \
		/../opt/local/include/glm/ext/matrix_float2x2.hpp \
		/../opt/local/include/glm/ext/matrix_float2x2_precision.hpp \
		/../opt/local/include/glm/trigonometric.hpp \
		/../opt/local/include/glm/detail/func_trigonometric.inl \
		/../opt/local/include/glm/detail/func_trigonometric_simd.inl \
		/../opt/local/include/glm/packing.hpp \
		/../opt/local/include/glm/detail/func_packing.inl \
		/../opt/local/include/glm/detail/type_half.hpp \
		/../opt/local/include/glm/detail/type_half.inl \
		/../opt/local/include/glm/detail/func_packing_simd.inl \
		/../opt/local/include/glm/integer.hpp \
		/../opt/local/include/glm/detail/func_integer.inl \
		/../opt/local/include/glm/detail/func_integer_simd.inl \
		/../opt/local/include/glm/simd/integer.h \
		/../opt/local/include/glm/gtx/transform.hpp \
		/../opt/local/include/glm/gtc/matrix_transform.hpp \
		/../opt/local/include/glm/ext/matrix_projection.hpp \
		/../opt/local/include/glm/gtc/constants.hpp \
		/../opt/local/include/glm/ext/scalar_constants.hpp \
		/../opt/local/include/glm/ext/scalar_constants.inl \
		/../opt/local/include/glm/gtc/constants.inl \
		/../opt/local/include/glm/ext/matrix_projection.inl \
		/../opt/local/include/glm/ext/matrix_clip_space.hpp \
		/../opt/local/include/glm/ext/matrix_clip_space.inl \
		/../opt/local/include/glm/ext/matrix_transform.hpp \
		/../opt/local/include/glm/ext/matrix_transform.inl \
		/../opt/local/include/glm/gtc/matrix_transform.inl \
		/../opt/local/include/glm/gtx/transform.inl \
		shader.h \
		/../opt/local/include/GLFW/glfw3native.h \
		imgui/imgui.h \
		imgui/imconfig.h \
		imgui/backends/imgui_impl_glfw.h \
		imgui/backends/imgui_impl_opengl3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

imgui.o: imgui/imgui.cpp imgui/imgui.h \
		imgui/imconfig.h \
		imgui/imgui_internal.h \
		imgui/imstb_textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui.o imgui/imgui.cpp

imgui_demo.o: imgui/imgui_demo.cpp imgui/imgui.h \
		imgui/imconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_demo.o imgui/imgui_demo.cpp

imgui_draw.o: imgui/imgui_draw.cpp imgui/imgui.h \
		imgui/imconfig.h \
		imgui/imgui_internal.h \
		imgui/imstb_textedit.h \
		imgui/misc/freetype/imgui_freetype.h \
		imgui/imstb_rectpack.h \
		imgui/imstb_truetype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_draw.o imgui/imgui_draw.cpp

imgui_tables.o: imgui/imgui_tables.cpp imgui/imgui.h \
		imgui/imconfig.h \
		imgui/imgui_internal.h \
		imgui/imstb_textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_tables.o imgui/imgui_tables.cpp

imgui_widgets.o: imgui/imgui_widgets.cpp imgui/imgui.h \
		imgui/imconfig.h \
		imgui/imgui_internal.h \
		imgui/imstb_textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_widgets.o imgui/imgui_widgets.cpp

imgui_impl_glfw.o: imgui/backends/imgui_impl_glfw.cpp imgui/imgui.h \
		imgui/imconfig.h \
		imgui/backends/imgui_impl_glfw.h \
		/../opt/local/include/GLFW/glfw3.h \
		/../opt/local/include/GLFW/glfw3native.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_impl_glfw.o imgui/backends/imgui_impl_glfw.cpp

imgui_impl_opengl3.o: imgui/backends/imgui_impl_opengl3.cpp imgui/imgui.h \
		imgui/imconfig.h \
		imgui/backends/imgui_impl_opengl3.h \
		imgui/backends/imgui_impl_opengl3_loader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgui_impl_opengl3.o imgui/backends/imgui_impl_opengl3.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/EngineProject/bin || mkdir -p $(INSTALL_ROOT)/opt/EngineProject/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/EngineProject/bin/EngineProject.app
	
	$(QINSTALL) EngineProject.app $(INSTALL_ROOT)/opt/EngineProject/bin/EngineProject.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/EngineProject/bin/EngineProject.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/EngineProject/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

